### ISSUE TITLE
Screen Clear is REPL dependant

### ISSUE THREAD

**Issue by gwa2100** [redwiz666/BavariaTheGame#17]
**Describe the bug**
The current screen clear is based on a repl.it lib.  Needs to be system based.

**To Reproduce**
N/a

**Expected behavior**
N/a

**Screenshots**
N/a

**Desktop (please complete the following information):**
v0.1D

**Additional context**
n/a

**Comment by redwiz666** [comment]
Modified clear screen to not use repl.it lib

https://github.com/redwiz666/BavariaTheGame/commit/29c1a3907f8dfa3e589b5e88187aab070166e3be
