### ISSUE TITLE
Fairie Fountains should disappear after use

### ISSUE THREAD

**Issue by gwa2100** [redwiz666/BavariaTheGame#5]
**Is your feature request related to a problem? Please describe.**
Fairie Fountains should disappear after use.  Currently they stay even after use, making it too easy to just return and heal.

**Describe the solution you'd like**
Make it so they disappear or they have only so many uses.

**Describe alternatives you've considered**
We can either have a limited number of uses/
or we can have it so that they disappear after one use.

**Additional context**
N/A

**Comment by redwiz666** [comment]
Make Faries disappear after discoving them

https://github.com/redwiz666/BavariaTheGame/commit/e565e4c9ae4b9957ab6fee6b87c92be4be335473
